let adminApp=null,adminAuth=null,adminFunctions=null,adminData={bookings:[],partners:[],supportTickets:[]};
function showSection(id,btn){document.querySelectorAll('.section').forEach(s=>s.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('aside button').forEach(b=>b.classList.remove('nav-active'));btn.classList.add('nav-active');if(id==='bookings')renderBookings();if(id==='partners')renderPartners();if(id==='support')renderSupport()}
function toast(t){const x=document.createElement('div');x.textContent=t;x.className='fixed bottom-6 left-1/2 -translate-x-1/2 bg-[#123c36] text-white px-5 py-3 rounded-2xl text-xs shadow-xl z-50';document.body.appendChild(x);setTimeout(()=>x.remove(),2500)}
function renderBookings(){const q=(document.getElementById('bookingSearch')?.value||'').toLowerCase();const rows=adminData.bookings.filter(b=>!q||JSON.stringify(b).toLowerCase().includes(q));const body=document.getElementById('bookingsBody');if(!rows.length){body.innerHTML='<tr><td colspan="6" class="p-10 text-center text-slate-500">No bookings returned.</td></tr>';return}body.innerHTML=rows.map(b=>{const status=String(b.status||'').toLowerCase();let action='—';if(status==='cancellation_requested')action='<div class="flex gap-2"><button onclick="resolveCancellation(\''+escAttr(b.id)+'\',\'approve\')" class="px-3 py-1.5 rounded-lg bg-red-50 text-red-700 font-bold">Approve cancel</button><button onclick="resolveCancellation(\''+escAttr(b.id)+'\',\'reject\')" class="px-3 py-1.5 rounded-lg bg-[#176b5b] text-white font-bold">Reject cancel</button></div>';else if(status==='completed'&&b.completionProofUrl){action=b.completionProofVerifiedAt?'<span class="text-emerald-700 font-bold">Proof verified</span>':'<button onclick="verifyCompletionProof(\''+escAttr(b.id)+'\')" class="px-3 py-1.5 rounded-lg bg-[#176b5b] text-white font-bold">Verify proof</button>'}return '<tr class="border-t border-[#edf5f1]"><td class="p-4 font-mono font-bold">'+esc(b.id)+'</td><td class="p-4">'+esc(b.name||b.customerId||'—')+'</td><td class="p-4">'+esc(b.service||'—')+'</td><td class="p-4">'+esc(b.for||'—')+'</td><td class="p-4 font-bold">'+esc(b.status||'—')+'</td><td class="p-4 text-xs">'+action+'</td></tr>'}).join('')}
function renderPartners(){const body=document.getElementById('partnersBody');if(!body)return;if(!adminData.partners.length){body.innerHTML='<tr><td colspan="5" class="p-10 text-center text-slate-500">No partners returned.</td></tr>';return}body.innerHTML=adminData.partners.map(p=>{const status=p.approvalStatus||(p.approved?'approved':'pending');const action=status==='approved'?'<button onclick="setApproval(\''+escAttr(p.id)+'\',\'suspend\')" class="px-3 py-1.5 rounded-lg border border-red-200 text-red-600 font-bold">Suspend</button>':'<button onclick="setApproval(\''+escAttr(p.id)+'\',\'approve\')" class="px-3 py-1.5 rounded-lg bg-[#176b5b] text-white font-bold">Approve</button>';return '<tr class="border-t border-[#edf5f1]"><td class="p-4 font-bold">'+esc(p.name||p.id)+'</td><td class="p-4">'+esc(p.phone||'—')+'</td><td class="p-4">'+esc((p.serviceCategories||[]).join(', ')||'—')+'</td><td class="p-4">'+esc(status)+'</td><td class="p-4">'+action+'</td></tr>'}).join('')}
function renderSupport(){const body=document.getElementById('supportBody');if(!body)return;body.innerHTML=adminData.supportTickets.length?adminData.supportTickets.map(t=>'<tr class="border-t border-[#edf5f1]"><td class="p-4 font-mono">'+esc(t.id)+'</td><td class="p-4">'+esc(t.customerId||'—')+'</td><td class="p-4">'+esc(t.subject||'—')+'</td><td class="p-4 font-bold">'+esc(t.status||'—')+'</td></tr>').join(''):'<tr><td colspan="4" class="p-10 text-center text-slate-500">No support tickets returned.</td></tr>'}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function escAttr(v){return String(v??'').replace(/[^A-Za-z0-9_-]/g,'')}
async function loadOperations(){if(!adminFunctions)return;try{const res=await adminFunctions.httpsCallable('adminListOperations')({limit:100});adminData=res.data||adminData;const s=adminData.stats||{};document.getElementById('statBookings').textContent=s.bookings||0;document.getElementById('statActive').textContent=s.activeBookings||0;document.getElementById('statPartners').textContent=s.partners||0;document.getElementById('statCompleted').textContent=s.completed||0;document.getElementById('statConfirmed').textContent=adminData.bookings.filter(b=>['partner_assigned','partner_on_the_way','service_started'].includes(String(b.status))).length;document.getElementById('backendStatus').innerHTML='<span class="w-2 h-2 rounded-full bg-emerald-500"></span> Firebase connected';renderBookings();renderPartners();renderSupport();toast('Live operations loaded')}catch(e){document.getElementById('backendStatus').innerHTML='<span class="w-2 h-2 rounded-full bg-red-400"></span> Admin auth required';toast(e.message||'Admin access required')}}
async function setApproval(id,decision){if(!adminFunctions)return;const note=prompt('Optional review note:','')||'';try{await adminFunctions.httpsCallable('setPartnerApproval')({partnerId:id,decision,note});await loadOperations();toast('Partner status updated')}catch(e){toast(e.message||'Approval update failed')}}
async function resolveCancellation(id,decision){if(!adminFunctions)return;const label=decision==='approve'?'approve this customer cancellation':'reject this customer cancellation';if(!confirm(label+'?'))return;try{await adminFunctions.httpsCallable('resolveBookingCancellation')({bookingId:id,decision});await loadOperations();toast('Cancellation updated')}catch(e){toast(e.message||'Cancellation update failed')}}
async function verifyCompletionProof(id){if(!adminFunctions)return;if(!confirm('Verify the completion proof for this booking?'))return;const note=prompt('Optional verification note:','Verified by operations')||'';try{await adminFunctions.httpsCallable('verifyBookingCompletionProof')({bookingId:id,note});await loadOperations();toast('Completion proof verified')}catch(e){toast(e.message||'Proof verification failed')}}
async function refreshDashboard(){await loadOperations()}
async function adminLogin(){const email=prompt('Admin email:');if(!email)return;const password=prompt('Admin password:');if(!password)return;try{await adminAuth.signInWithEmailAndPassword(email.trim(),password);toast('Signed in');await loadOperations()}catch(e){toast(e.message||'Admin login failed')}}
async function adminLogout(){if(adminAuth)await adminAuth.signOut()}
async function initAdmin(){const cfg=window.NEAR_FAMILY_FIREBASE_CONFIG;if(!cfg?.projectId||cfg.projectId.startsWith('REPLACE_')){document.getElementById('backendStatus').innerHTML='<span class="w-2 h-2 rounded-full bg-amber-400"></span> Firebase config required';return}if(!firebase.apps.length)firebase.initializeApp(cfg);adminApp=firebase.app();adminAuth=firebase.auth();adminFunctions=firebase.functions();adminAuth.onAuthStateChanged(async user=>{if(user){await loadOperations()}else{document.getElementById('backendStatus').innerHTML='<span class="w-2 h-2 rounded-full bg-amber-400"></span> Admin sign-in required'}})}
window.addEventListener('load',initAdmin);
