function openBooking(){closeService();let s=state.selected;if(!s)return;$('photos').value='';if(state.familyBookingTarget){$('forWho').value='Family';updateFamilyOptions();const idx=Number(state.familyBookingTarget.index);if(Number.isInteger(idx)&&state.families[idx])$('familySelect').value=String(idx)}else{$('forWho').value='Me';updateFamilyOptions()}$('bookingSummary').innerHTML=`<div class="bg-[#dcefe7] rounded-2xl p-4"><b>${s.n}</b><p class="text-xs text-[#638079]">${s.c}</p></div>`;$('sumService').textContent=s.n;$('sumPrice').textContent='₹'+s.p;$('sumTotal').textContent='₹'+s.p;$('bookingName').value=state.user?.name||'';$('bookingPhone').value=state.user?.phone||'';let today=new Date().toISOString().slice(0,10);$('bookingDate').min=today;$('bookingDate').value=today;populateAddresses();updateFamilyOptions();$('bookingModal').classList.add('show')}

function closeBooking(){$('bookingModal').classList.remove('show')}

function resetBookingForm(){
  state.familyBookingTarget=null;
  $('forWho').value='Me';
  $('familySelect').value='';
  $('familySelect').classList.add('hide');
  $('bookingName').value=state.user?.name||'';
  $('bookingPhone').value=state.user?.phone||'';
  $('addressSelect').value='';
  $('newAddress').value='';
  $('bookingTime').value='10:00 AM - 12:00 PM';
  $('instructions').value='';
  $('photos').value='';
  state.familyBookingTarget=null;
}

function populateAddresses(){const a=state.addresses.map(x=>typeof x==='string'?x:(x?.address||'')).map(x=>String(x||'').trim()).filter(Boolean);const unique=[...new Set(a)];$('addressSelect').innerHTML='<option value="">Select saved address</option>'+unique.map(x=>`<option value="${escapeHtml(x)}">${escapeHtml(x)}</option>`).join('')}

function updateFamilyOptions(){let fam=$('forWho').value==='Family';$('familySelect').classList.toggle('hide',!fam);const select=$('familySelect');select.innerHTML='';if(fam){state.families.forEach((f,i)=>{const option=document.createElement('option');option.value=String(i);option.textContent=String(f.name||'Family')+' — '+String(f.relationship||'Family');select.appendChild(option)})}if(fam&&!state.families.length){toast('Add a family member first.');closeBooking();openFamily();}}

async function confirmBooking(){
  const s=state.selected,name=$('bookingName').value.trim(),phone=$('bookingPhone').value.trim(),addr=$('newAddress').value.trim()||$('addressSelect').value,date=$('bookingDate').value,time=$('bookingTime').value;
  if(!s)return toast('Please select a service first.');if(!name)return toast('Please enter your full name.');if(phone.replace(/\D/g,'').length<10)return toast('Please enter a valid mobile number.');if(!addr)return toast('Please select or enter a service address.');if(!date)return toast('Please select a service date.');if(date<new Date().toISOString().slice(0,10))return toast('Please select today or a future date.');if(state.bookingSubmitting)return toast('Your request is already being submitted. Please wait.');
  let target='Me',familyMemberId=null;
  if($('forWho').value==='Family'){const idx=Number($('familySelect').value);const f=state.families[idx];if(!f)return toast('Please select a family member.');target=f.name+' ('+f.relationship+')';familyMemberId=f.id||null}
  const selectedFiles=Array.from($('photos').files||[]).slice(0,5);if(selectedFiles.some(f=>!f.type.startsWith('image/')))return toast('Only image files can be uploaded.');if(selectedFiles.some(f=>f.size>8*1024*1024))return toast('Each photo must be 8 MB or smaller.');
  state.bookingSubmitting=true;const submitButton=[...document.querySelectorAll('#bookingModal button')].find(b=>b.textContent.trim()==='Confirm Request');if(submitButton){submitButton.disabled=true;submitButton.textContent='Submitting...';submitButton.classList.add('opacity-60','cursor-not-allowed')}
  try{
    const savedAddress=state.addresses.find(x=>(typeof x==='string'?x:x.address)===addr);
    const addressId=(savedAddress&&typeof savedAddress==='object'&&savedAddress.id)?String(savedAddress.id):null;
    const clientRequestId=(window.crypto&&typeof window.crypto.randomUUID==='function')?window.crypto.randomUUID():('nf_'+Date.now()+'_'+Math.random().toString(36).slice(2,14));
    const payload={service:s.n,category:s.c,price:s.p,name,phone,for:target,forWho:$('forWho').value,familyMemberId,address:addr,addressId,clientRequestId,date,time,instructions:$('instructions').value.trim(),photos:[],location:(state.location.lat!=null&&state.location.lng!=null)?{lat:Number(state.location.lat),lng:Number(state.location.lng),label:state.location.label||'Current location'}:null};
    let b;
    if(NearFamilyBackend.ready){
      const id=await NearFamilyBackend.createBooking(payload);b={...payload,id,status:'requested',createdAt:new Date().toISOString()};
      if(id)b.id=id;
      if(selectedFiles.length){toast('Uploading photos...');b.photos=await NearFamilyBackend.uploadBookingPhotos(b.id,selectedFiles);await NearFamilyBackend.attachBookingPhotos(b.id,b.photos)}
    }else{
      b={...payload,id:'NF-'+Date.now().toString().slice(-8),status:'requested',createdAt:new Date().toISOString()};
    }
    state.bookings.unshift(b);
    const newAddress=$('newAddress').value.trim();
    if(newAddress&&!state.addresses.some(x=>(typeof x==='string'?x:x.address)===addr)){
      if(NearFamilyBackend.ready){const addressId=await NearFamilyBackend.saveAddress(addr);state.addresses.unshift({id:addressId,address:addr})}else state.addresses.unshift(addr);
    }
    save();closeBooking();resetBookingForm();$('successText').textContent=s.n+' for '+target+' has been requested for '+date+' • '+time+'. Booking ID: '+b.id;$('successModal').classList.add('show');renderAll();
  }catch(e){console.error('Booking submission failed',e);toast(e?.message||'We could not submit the request. Please try again.')}
  finally{state.bookingSubmitting=false;if(submitButton){submitButton.disabled=false;submitButton.textContent='Confirm Request';submitButton.classList.remove('opacity-60','cursor-not-allowed')}}
}

function renderBookings(){let el=$('bookingsList');if(!state.bookings.length){el.innerHTML='<div class="bg-white border border-[#dcefe7] rounded-3xl p-8 text-center"><div class="text-3xl">📅</div><h3 class="font-black mt-3">No bookings yet</h3><p class="text-xs text-slate-500 mt-1">Choose a service and request help when you need it.</p><button onclick="go(\'home\')" class="mt-4 bg-[#176b5b] text-white px-5 py-3 rounded-xl font-bold text-sm">Explore Services</button></div>';return}el.innerHTML=state.bookings.map(b=>`<article class="bg-white border border-[#dcefe7] rounded-3xl p-5 soft"><div class="flex justify-between gap-3"><div><span class="text-[10px] font-bold text-[#176b5b]">${escapeHtml(b.category)}</span><h3 class="font-black mt-1">${escapeHtml(b.service)}</h3><p class="text-xs text-slate-500 mt-1">For: ${escapeHtml(b.for)}</p></div><span class="h-fit text-[10px] font-bold bg-[#dcefe7] text-[#176b5b] px-3 py-1 rounded-full">${bookingStatusLabel(b.status)}</span></div><div class="mt-4 h-1.5 rounded-full bg-[#dcefe7] overflow-hidden"><div class="h-full bg-[#176b5b]" style="width:${bookingStep(b.status)===-1?0:((bookingStep(b.status)+1)/5*100)+'%'}"></div></div><div class="grid grid-cols-2 gap-3 mt-4 text-xs"><div>📍 ${escapeHtml(b.address)}</div><div>🗓 ${escapeHtml(b.date)}<br>⏰ ${escapeHtml(b.time)}</div></div><div class="mt-4 pt-3 border-t border-[#dcefe7] flex justify-between items-center"><span class="font-black">₹${escapeHtml(b.price)}</span><button onclick="viewBooking('${b.id}')" class="text-[#176b5b] font-bold text-xs">Track request →</button></div></article>`).join('')}

function bookingStep(status){const map={requested:0,'Request Confirmed':0,searching_partner:1,partner_assigned:1,partner_on_the_way:2,service_started:3,completed:4,Completed:4,cancelled:-1,cancellation_requested:-1};return map[status]??0}

function bookingStatusLabel(status){const map={requested:'Request Confirmed',searching_partner:'Finding a partner',partner_assigned:'Partner Assigned',partner_on_the_way:'Partner On The Way',service_started:'Service Started',completed:'Completed',Completed:'Completed',cancelled:'Cancelled',cancellation_requested:'Cancellation Requested'};return map[status]||status||'Request Confirmed'}

function viewBooking(id){let b=state.bookings.find(x=>x.id===id);if(!b)return;const current=bookingStep(b.status),steps=['Request Confirmed','Partner Assigned','Partner On The Way','Service Started','Completed'],canCancel=!['completed','Completed','cancelled','cancellation_requested'].includes(String(b.status));$('serviceDetail').innerHTML=`<div class="text-center"><div class="w-14 h-14 bg-[#dcefe7] rounded-full text-[#176b5b] flex items-center justify-center mx-auto text-xl">${current===-1?'!':'✓'}</div><h2 class="text-2xl font-black mt-3">${bookingStatusLabel(b.status)}</h2><p class="text-xs text-slate-500">${escapeHtml(b.id)}</p></div><div class="mt-5 space-y-3 text-sm"><div><b>Service</b><p>${escapeHtml(b.service)}</p></div><div><b>For</b><p>${escapeHtml(b.for)}</p></div><div><b>When</b><p>${escapeHtml(b.date)} • ${escapeHtml(b.time)}</p></div><div><b>Where</b><p>${escapeHtml(b.address)}</p></div><div><b>Instructions</b><p>${escapeHtml(b.instructions||'—')}</p></div></div><div class="mt-6 bg-[#f7fcfa] rounded-2xl p-4"><b>Booking progress</b><div class="mt-4 space-y-3 text-xs">${steps.map((label,i)=>`<div class="flex items-center gap-3"><span class="w-7 h-7 rounded-full flex items-center justify-center ${current>=i?'bg-[#176b5b] text-white':'bg-[#dcefe7] text-[#638079]'}">${current>=i?'✓':i+1}</span><span class="${current>=i?'font-bold text-[#176b5b]':'text-slate-400'}">${label}</span></div>`).join('')}${current===-1?'<p class="mt-3 text-red-600 font-bold">This request has been cancelled.</p>':b.status==='cancellation_requested'?'<p class="mt-3 text-amber-700 font-bold">Cancellation request submitted. We will update you when it is resolved.</p>':''}</div><div class="mt-4 flex gap-2 flex-wrap justify-center">${canCancel?'<button class="px-4 py-2 rounded-xl border font-bold text-sm" onclick="requestBookingCancellation(\''+b.id+'\')">Request cancellation</button>':''}<button class="px-4 py-2 rounded-xl border font-bold text-sm" onclick="rebookBooking(\''+b.id+'\')">Rebook</button></div></div>${b.partnerId?'<div class="mt-4 bg-white border border-[#dcefe7] rounded-2xl p-4 text-xs"><b>Partner assigned</b><p class="text-slate-500 mt-1">Your service partner has been assigned. Live partner details will appear here when enabled.</p></div>':''}`;$('serviceModal').classList.add('show')}

async async function requestBookingCancellation(id){const b=state.bookings.find(x=>x.id===id);if(!b||['completed','cancelled','cancellation_requested'].includes(b.status))return;if(!confirm('Request cancellation for this booking?'))return;if(window.NearFamilyBackend?.ready){try{await NearFamilyBackend.requestBookingCancellation(id);b.status='cancellation_requested';b.cancellationRequestedAt=new Date().toISOString();b.updatedAt=new Date().toISOString();save();renderAll();if($('bookingModal')?.classList.contains('show'))viewBooking(id);toast('Cancellation request submitted')}catch(e){console.warn(e);toast('Cancellation request could not be submitted')}}else{b.status='cancellation_requested';b.cancellationRequestedAt=new Date().toISOString();b.updatedAt=new Date().toISOString();save();renderAll();if($('bookingModal')?.classList.contains('show'))viewBooking(id);toast('Cancellation request saved locally')}}\n

function rebookBooking(id){const b=state.bookings.find(x=>x.id===id);if(!b)return;const s=SERVICES.find(x=>x.n===b.service)||{id:0,n:b.service,c:b.category,p:b.price,d:'',i:''};state.selected=s;let rebookFamilyIndex=-1;if(b.familyMemberId)rebookFamilyIndex=state.families.findIndex(f=>f.id===b.familyMemberId);if(rebookFamilyIndex<0&&b.forWho==='Family'&&b.for){let who=String(b.for).split(' (')[0].trim();rebookFamilyIndex=state.families.findIndex(f=>f.name===who)}state.familyBookingTarget=rebookFamilyIndex>=0?{id:state.families[rebookFamilyIndex].id||null,index:rebookFamilyIndex,name:state.families[rebookFamilyIndex].name}:null;closeService();$('bookingSummary').innerHTML='<div class="bg-[#dcefe7] rounded-2xl p-4"><b>'+s.n+'</b><p class="text-xs text-[#638079]">'+s.c+'</p></div>';$('sumService').textContent=s.n;$('sumPrice').textContent='₹'+s.p;$('sumTotal').textContent='₹'+s.p;$('bookingName').value=state.user?.name||b.name||'';$('bookingPhone').value=state.user?.phone||b.phone||'';let today=new Date().toISOString().slice(0,10);$('bookingDate').min=today;$('bookingDate').value=today;$('bookingTime').value=b.time||'10:00 AM - 12:00 PM';$('newAddress').value=b.address||'';$('instructions').value=b.instructions||'';$('forWho').value=b.forWho||'Me';updateFamilyOptions();let idx=-1;if(b.familyMemberId)idx=state.families.findIndex(f=>f.id===b.familyMemberId);if(idx<0&&b.forWho==='Family'&&b.for){let who=String(b.for).split(' (')[0].trim();idx=state.families.findIndex(f=>f.name===who)}if(idx>=0){$('forWho').value='Family';updateFamilyOptions();$('familySelect').value=String(idx)}$('bookingModal').classList.add('show')}\n
