function openFamily(){renderFamilyModal();$('familyModal').classList.add('show')}

function closeFamily(){$('familyModal').classList.remove('show')}

function renderFamilyModal(){$('familyModalList').innerHTML=state.families.length?state.families.map((f,i)=>`<button onclick="selectFamily(${i})" class="bg-[#f7fcfa] border border-[#dcefe7] rounded-2xl p-4 text-left"><div class="w-10 h-10 rounded-xl bg-[#dcefe7] text-[#176b5b] flex items-center justify-center">${f.relationship==='Dad'?'👨':f.relationship==='Mom'?'👩':'❤️'}</div><b class="block mt-2">${escapeHtml(f.name)}</b><span class="text-xs text-slate-500">${escapeHtml(f.relationship)}</span></button>`).join(''):'<p class="col-span-2 text-center text-sm text-slate-500 py-6">No family members saved yet.</p>'}

async function addFamily(){let name=(prompt('Family member name:')||'').trim();if(!name)return;if(name.length>80)return toast('Family member name is too long.');let rel=(prompt('Relationship (Mom, Dad, Grandma, etc.):','Dad')||'').trim()||'Family';if(rel.length>40)return toast('Relationship is too long.');let phone=(prompt('Phone number:','')||'').trim();if(phone&&phone.replace(/\\D/g,'').length<10)return toast('Please enter a valid phone number or leave it blank.');let address=(prompt('Address/locality:','')||'').trim();if(address.length>300)return toast('Address is too long.');let family={name,relationship:rel,phone,address};state.families.push(family);if(address&&!state.addresses.includes(address))state.addresses.push(address);save();if(NearFamilyBackend.ready){try{const familyId=await NearFamilyBackend.saveFamilyMember(family);if(familyId)family.id=familyId;if(address)await NearFamilyBackend.saveAddress(address);save()}catch(e){console.warn('Cloud family save failed; keeping local copy',e)}}renderAll();renderFamilyModal();toast(name+' added to your family')}

function selectFamily(i){let f=state.families[i];if(!f)return;closeFamily();state.selected=null;state.familyBookingTarget={id:f.id||null,index:i,name:f.name};go('home');toast('Choose a service for '+f.name);setTimeout(()=>{const first=$('services')?.querySelector('button');if(first)first.scrollIntoView({behavior:'smooth',block:'center'})},120)}

function renderFamilyPage(){$('familyCards').innerHTML=state.families.length?state.families.map((f,i)=>{const name=escapeHtml(f.name||'Family Member'),relationship=escapeHtml(f.relationship||'Family'),phone=escapeHtml(f.phone||'Not added'),address=escapeHtml(f.address||'Address not added');return `<div class="bg-white border border-[#dcefe7] rounded-3xl p-5 soft"><div class="flex justify-between"><div><div class="w-11 h-11 rounded-xl bg-[#dcefe7] text-[#176b5b] flex items-center justify-center">♥</div><h3 class="font-black mt-3">${name}</h3><p class="text-xs text-slate-500">${relationship}</p></div><button onclick="removeFamily(${i})" class="text-red-400" aria-label="Remove family member">×</button></div><p class="text-xs mt-4">📞 ${phone}</p><p class="text-xs mt-1">📍 ${address}</p><button onclick="selectFamily(${i})" class="w-full mt-4 bg-[#176b5b] text-white py-2.5 rounded-xl text-xs font-bold">Request Help</button></div>`}).join(''):'<div class="sm:col-span-2 bg-white rounded-3xl border border-[#dcefe7] p-8 text-center text-sm text-slate-500">Add Mom, Dad or another family member to request help quickly.</div>'}

async function editFamily(i){const f=state.families[i];if(!f)return;const name=(prompt('Family member name:',f.name||'')||'').trim();if(!name)return;const rel=(prompt('Relationship:',f.relationship||'Family')||'').trim()||'Family';const phone=(prompt('Phone number:',f.phone||'')||'').trim();const address=(prompt('Address/locality:',f.address||'')||'').trim();const updated={...f,name,relationship:rel,phone,address};state.families[i]=updated;save();if(NearFamilyBackend.ready&&f.id){try{await NearFamilyBackend.saveFamilyMember(updated,f.id);toast('Family member updated')}catch(e){state.families[i]=f;save();toast('Could not update family member')}}else toast('Family member updated');renderAll()}

async function removeFamily(i){const f=state.families[i];if(!f)return;if(!confirm('Remove '+f.name+' from your family list?'))return;if(NearFamilyBackend.ready&&f.id){try{await NearFamilyBackend.deleteFamilyMember(f.id)}catch(e){toast('Could not remove family member');return}}state.families.splice(i,1);save();renderAll();toast(f.name+' removed')}
